dist: bionic

language: cpp

compiler:
  - gcc

before_script:
  # configure
  - mkdir build && cd build
  - cmake -DBUILD_TEST=ON -DBUILD_EXAMPLES=ON ..

script:
  # build
  - make
  # run tests
  - make test