dist: bionic

language: cpp

compiler:
  - gcc

env:
  - CC=gcc-8 CXX=g++-8

before_install:
  # install dependencies
  - sudo apt-get -y install libeigen3-dev g++-8 gcc-8 python3-pip
  - pip3 install -r requirements.txt

before_script:
  # configure
  - mkdir build && cd build
  - cmake -DBUILD_TEST=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Debug ..

script:
  # build
  - make
  # run tests
  - make test