dist: bionic

language: cpp

compiler:
  - gcc

before_script:
  # configure
  - mkdir build
  - cmake -S . -B build -DBUILD_TEST=ON

script:
  # build
  - cmake --build build
  # run tests
  - cmake --build build --target test