dist: focal

language: cpp

compiler:
  - gcc

before_install:
  # install dependencies
  - sudo apt-get -y install libeigen3-dev

before_script:
  # configure
  - mkdir build && cd build
  - cmake -DBUILD_TEST=ON -DBUILD_PLOTS=OFF -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Debug ..

script:
  # build
  - make
  # run tests
  - make test